#!/bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

# Configura monitores (HDMI-1 izquierda, eDP-1 derecha y principal)
xrandr --output HDMI-1 --mode 1920x1080 --pos 00x0 --rotate normal \
       --output eDP-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal

# Renombrar monitores para uso en bspwm (opcional)
bspc monitor HDMI-1 -n monitor1
bspc monitor eDP-1 -n monitor0

# Asigna escritorios a monitores
bspc monitor monitor0 -d I II III IV V VI VII VIII IX
bspc monitor monitor1 -d X

# Enfoca el escritorio inicial de cada monitor
bspc monitor monitor0 -f I
bspc monitor monitor1 -f X

# Configuración general bspwm
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Reglas para ventanas
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Fondo de pantalla
feh --bg-fill ~/Wallpaper/default.png &

# Polybar
~/.config/polybar/launch.sh

# Picom compositor
picom &

# Cursor
xsetroot -cursor_name left_ptr &

# Iniciar udiskie
udiskie -t &

# Inicia bspwm
exec bspwm

