#!/bin/sh

# Ruta de salida de las capturas
output=~/ScreenShots/%Y-%m-%d-%T-screenshot.png

# Crear carpeta si no existe
mkdir -p ~/ScreenShots

# Tipo de captura según el primer argumento
case "$1" in
    "select")
        scrot -s -q 100 -l mode=classic "$output" || exit
        ;;
    "window")
        scrot -q 100 --focused -b "$output" || exit
        ;;
    *)
        scrot "$output" || exit
        ;;
esac

# Notificación
notify-send "Screenshot taken."